export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const SHIPPING_INFO = "SHIPPING_INFO";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
